### ISSUE TITLE
Misspell the repo name?

### ISSUE THREAD

**Issue by aidistan** [songpeng/songpeng.github.io#1]
The name of this repo looks strange. Maybe you should name it `songpeng.github.io` instead of `songpeng.github.com`?

Then the code on `master` branch will be served by Jekyll on `http://songpeng.github.io`.

**Comment by songpeng** [comment]
Hi, Aidi,
Thanks for your suggestion. I created this repo several months ago following the tutorial online. 
Now, I fixed it ~
Songpeng
